/* @lintuxt - September 2021 - NO WARRANTY - ISC License */

#pragma once

#define MASTER_RIGHT

#define USE_SERIAL_PD2

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 100

#ifdef RGB_MATRIX_ENABLE
  #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
  #define RGB_MATRIX_HUE_STEP 10
  #define RGB_MATRIX_SAT_STEP 4
  #define RGB_MATRIX_VAL_STEP 4
  #define RGB_MATRIX_SPD_STEP 10

  #define DISABLE_RGB_MATRIX_BREATHING
  #define DISABLE_RGB_MATRIX_BAND_SAT
  #define DISABLE_RGB_MATRIX_BAND_VAL
  #define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
  #define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
  #define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
  #define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
  #define DISABLE_RGB_MATRIX_RAINDROPS
  #define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
  #define DISABLE_RGB_MATRIX_HUE_BREATHING
  #define DISABLE_RGB_MATRIX_RAINBOW_BEACON
  #define DISABLE_RGB_RGB_MATRIX_CYCLE_SPIRAL
  #define DISABLE_RGB_MATRIX_HUE_PENDULUM
#endif

#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"

