MCU = atmega32u4
BOOTLOADER = caterina

BOOTMAGIC_ENABLE = no 		# Modified
MOUSEKEY_ENABLE = no		# Modified
EXTRAKEY_ENABLE = no		# Modified
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no			# Modified
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = yes		# Modified
RGB_MATRIX_DRIVER = WS2812

DEFAULT_FOLDER = crkbd/rev1

RGBLIGHT_SUPPORTED = no		# Modified
RGB_MATRIX_SUPPORTED = yes

LAYOUTS = split_3x5_3 split_3x6_3

OLED_ENABLE = yes
